HomeLibrary.WebMvc/Controllers/BookController.cs
using HomeLibrary.Models.Book;
using HomeLibrary.Services.Book;
using HomeLibrary.Services.Genre;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HomeLibrary.WebMvc.Controllers;

public class BookController : Controller
{
    //used to do the indirect Db interaction
    //adding an instance of the BookService class to retrieve data from the Db
    private IBookService _service;
    private IGenreService _genreService;

    // the parameters are dependency injections for the book service and genre service
    public BookController(IBookService service, IGenreService genreService)
    {
        _service = service;
        _genreService = genreService;
    }

    //Controller method that is called when the "index" page is requested by a reader(user)
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        //getting a list of books from the Db
        var book = await _service.GetAllBooksAsync();
        return View(book);
    }

    [HttpGet]
    public async Task<IActionResult> Create()
    {
        //getting all genres from the _genreService
        var genres = await _genreService.GetAllGenresAsync();
        //Converting the list of genres from _GenreService into a list of SelectList items, each will be an option in a dropdown list
        var selectList = genres.Select(g => new SelectListItem(g.Genre, g.Id.ToString())).ToList();
        //this is a "Dictionary" that is used to pass data from this controller to the Create View
        ViewData["Genres"] = selectList;
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(BookCreate model)
    {
        if (!ModelState.IsValid)
            return View(model);

        await _service.CreateBookAsync(model);

        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public async Task<IActionResult> Details(int id)
    {
        //calling the service method and storing the detail model
        BookDetail? model = await _service.GetBooksByIdAsync(id);

        //if not found, will be returned to the not found view
        if (model is null)
            return NotFound();

        //if found, returns the model VIEW
        return View(model);
    }

    // GET Update

    [HttpGet]

    public async Task<IActionResult> Update(int id)
    {
        BookDetail? book = await _service.GetBooksByIdAsync(id);
        if (book is null)
            return NotFound();

        //if not null, will now create a BookUpdate model from the Book data object to load into view
        BookUpdate model = new()
        {
            Id = book.Id,
            Title = book.Title,
            Author = book.Author,
            SeriesNumber = book.SeriesNumber,
            GenreId = book.GenreId,
            Comment = book.Comment,
            DateFinished = book.DateFinished
        };
        return View(model);
    }

    // POST Update

    [HttpPost]

    // method takes in the Id of the Book AND the BookUpdate model because it contains the new data
    public async Task<IActionResult> Update(int id, BookUpdate model)
    {
        if (!ModelState.IsValid)
            return View(model);

        if (await _service.UpdateBookAsync(model))
            return RedirectToAction(nameof(Details), new { id = id });

        ModelState.AddModelError("Save Error", "Could not update the book. Please try again.");
        return View(model);
    }

    // GET Delete

    [HttpGet]

    public async Task<IActionResult> Delete(int id)
    {
        BookDetail? book = await _service.GetBooksByIdAsync(id);
        if (book is null)
            return RedirectToAction(nameof(Index));

        return View(book);
    }

    //POST Delete
    [HttpPost]

    [ActionName(nameof(Delete))] //connecting the method Confirm Delete with the Delete Action
    public async Task<IActionResult> ConfirmDelete(int id)
    {
        await _service.DeleteBooksByIdAsync(id);
        return RedirectToAction(nameof(Index));

    }
}

HomeLibrary.WebMvc/Controllers/GenreController.cs
using HomeLibrary.Models.Genre;
using HomeLibrary.Services.Genre;
using Microsoft.AspNetCore.Mvc;

namespace HomeLibrary.WebMvc.Controllers;

public class GenreController : Controller
{
    private readonly IGenreService _service;

    public GenreController(IGenreService service)
    {
        _service = service;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        List<GenreListItem> genres = await _service.GetAllGenresAsync();
        return View(genres);
    }

    // Returning the Create View
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    // POST Create
    // taking in the form data from the Create View (Genre)
    [HttpPost]
    public async Task<IActionResult> Create(GenreCreate model)
    {
        if (!ModelState.IsValid)
            return View(model);

        //calling service method to create a glorious new Genre
        await _service.CreateGenreAsync(model);

        return RedirectToAction(nameof(Index));
    }

    // GET Update method
    [HttpGet]
    public async Task<IActionResult> Update(int id)
    {
        GenreDetail genre = await _service.GetGenreAsync(id);

        GenreUpdate model = new()
        {
            Id = genre.Id,
            Genre = genre.Genre
        };

        return View(model);
    }


    [HttpPost]
    public async Task<IActionResult> Update(int id, GenreUpdate model)
    {
        if (!ModelState.IsValid)
            return View(model);

        if (await _service.UpdateGenreAsync(model))
            return RedirectToAction(nameof(Index), new { id = id });

        ModelState.AddModelError("Save Error", "Could not update the Genre details.  Please try again.");
        return View(model);
    }

    // GET Delete method
    [HttpGet]

    public async Task<IActionResult> Delete(int id)
    {
        GenreDetail genre = await _service.GetGenreAsync(id);
        if (genre is null)
            return RedirectToAction(nameof(Index));

        return View(genre);
    }

    //POST Delete
    [HttpPost]

    [ActionName(nameof(Delete))] //connecting the method Confirm Delete with the Delete Action
    public async Task<IActionResult> ConfirmDelete(int id)
    {
        await _service.DeleteGenreAsync(id);
        return RedirectToAction(nameof(Index));

    }
}

HomeLibrary.WebMvc/Controllers/WishListController.cs
using HomeLibrary.Models.WishList;
using HomeLibrary.Services.WishList;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HomeLibrary.WebMvc.Controllers;

public class WishListController : Controller
{
    //instance of the WishListService class needed to retrieve data from the Db
    //created a constructor for the controller that takes an instance of IWishListServie and saves as a private field
    //Using this to do the indirect Db interaction
    private IWishListService _service;
    public WishListController(IWishListService service)
    {
        _service = service;
    }

    //A GET endpoint to get the Create View
    //CREATE View holds the HTML form that will be used to create 
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(WishListCreate model)
    {
        if (!ModelState.IsValid)
            return View(model);

        await _service.CreateWishListAsync(model);

        return RedirectToAction(nameof(Index));
    }

    //WishList method for GET Index endpoint
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        List<WishListDetail> wishlist = (List<WishListDetail>)await _service.GetAllWishListAsync(); //don't understand the fix here
        return View(wishlist);
    }

    //WishList GET for update method
    [HttpGet]
    public async Task<IActionResult> Update(int id)
    {
        WishListDetail wishlist = await _service.GetWishListByIdAsync(id);

        WishListUpdate model = new()
        {
            Id = wishlist.Id,
            Title = wishlist.Title,
            Author = wishlist.Author,
            SeriesNumber = wishlist.SeriesNumber,
            Genre = wishlist.Genre,
        };

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Update(int id, WishListUpdate model)
    {
        if (!ModelState.IsValid)
            return View(model);

        if (await _service.UpdateWishListAsync(model))
            return RedirectToAction(nameof(Index), new { id = id });

        ModelState.AddModelError("Save Error", "Could not update the book details.  Please try again.");
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Delete(int id)
    {
        WishListDetail? wishlist = await _service.GetWishListByIdAsync(id);
        if (wishlist is null)
            return RedirectToAction(nameof(Index));

        return View(wishlist);
    }

    [HttpPost]
    [ActionName(nameof(Delete))]//ActionName connects the method (ConfirmDelete) to the ConfirmDelete action

    public async Task<IActionResult> ConfirmDelete(int id)
    {
        await _service.DeleteWishListByIdAsync(id);
        return RedirectToAction(nameof(Index));
    }
}

HomeLibrary.WebMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HomeLibrary.WebMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HomeLibrary.WebMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HomeLibrary App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         @if (User.Identity?.IsAuthenticated == true)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-action="Index" asp-controller="WishList">WishList</a>
                            </li>
                              <li class="nav-item">
                                <a class="nav-link text-dark" asp-action="Index" asp-controller="Genre">Genres</a>
                            </li>
                             <li class="nav-item">
                                <a class="nav-link text-dark" asp-action="Index" asp-controller="Book">Library</a>
                            </li>
                        }
                    </ul>

                        <partial name="_LoginPartial.cshtml" />

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HomeLibrary.WebMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>